### ISSUE TITLE
What's the difference between control_domain and remote_host?

### ISSUE THREAD

**Issue by mebest100** [projectarkc/arkc-client#3]
What's the difference between control_domain and remote_host?
What I mean is what's function of control_domain, how can I specify my VPS IP clearly into client json file?

Another question is what's the local listening port for client, is it http:127.0.0.1:8001?

And why it say mismatched external address while I already enabled upnp on router?
WARNING: 2016-03-04 19:35:09,011; Mismatched external address, more than one layers of NAT? UPnP may not work.

**Comment by tebaarkc** [comment]
Hi, yuan78,

Thank you for trying ArkC. Regarding to your questions:
1.  remote_host is the address on which ArkC client listens for connections
from ArkC server, while control_domain is the domain of ArkC server. For
the time being, since ArkC uses DNS requests to activate the server, your
VPS must have a domain name (with NS records set) to serve as ArkC server,
or DNS requests will not be received.
2. The local listening port is for the end user, i.e. set HTTP proxy to
127.0.0.1:8001 in your web browser to use the proxy.
3. As the message implies, you may have more that one layers of NAT (that
of your home router and that imposed by your ISP). We are working actively
to enable TCP punching through multiple layers of NAT ;-)

**Comment by mebest100** [comment]
Hi Tebaarkc,
Thanks a lot for your quick reply, look forward to your good news for improvements of multiple layers of NAT.
But can I just disable upnp for arkcclient for time being?
